-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Laitos CASCADE;
DROP TABLE IF EXISTS Org_luokka CASCADE;
DROP TABLE IF EXISTS Kysymys CASCADE;
DROP TABLE IF EXISTS Opiskelija CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Kysely CASCADE;
DROP TABLE IF EXISTS Osallistumislista CASCADE;
DROP TABLE IF EXISTS Kyselylista CASCADE;
DROP TABLE IF EXISTS Vastauslista CASCADE;
DROP TABLE IF EXISTS Kysymyslista CASCADE;